# Generated by Django 2.0.5 on 2020-06-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0001_initial'),
        ('photoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.ManyToManyField(to='userapp.PhotoUser'),
        ),
        migrations.AddField(
            model_name='photo',
            name='views',
            field=models.ManyToManyField(to='photoapp.PhotoViews'),
        ),
    ]
