# Generated by Django 2.2.10 on 2020-04-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
        ('photoapp', '0002_auto_20200415_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='user',
            field=models.ManyToManyField(to='userapp.PhotoUser'),
        ),
        migrations.AddField(
            model_name='photo',
            name='views',
            field=models.ManyToManyField(to='photoapp.PhotoViews'),
        ),
    ]
