# Generated by Django 2.0.5 on 2020-06-23 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0003_photo_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_upload', models.DateTimeField(auto_now_add=True)),
                ('photos', models.ManyToManyField(to='photoapp.Photo')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='upload_list',
            field=models.ManyToManyField(to='photoapp.UploadList'),
        ),
    ]
