# Generated by Django 2.2.10 on 2020-04-14 10:32

from django.db import migrations, models
import photoapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0003_auto_20200414_0723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(),
        ),
    ]
