# Generated by Django 2.0.5 on 2020-06-23 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0006_auto_20200623_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoposition',
            name='photo_with_position',
        ),
    ]
