# Generated by Django 2.0.5 on 2020-06-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0007_remove_photoposition_photo_with_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoposition',
            name='photo_with_position',
            field=models.ManyToManyField(to='photoapp.Photo'),
        ),
        migrations.RemoveField(
            model_name='photo',
            name='position',
        ),
        migrations.AddField(
            model_name='photo',
            name='position',
            field=models.ManyToManyField(to='photoapp.PhotoPosition'),
        ),
    ]
