# Generated by Django 2.0.5 on 2020-06-23 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_photouser_upload_lists'),
        ('photoapp', '0008_auto_20200623_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadlist',
            name='user',
            field=models.ManyToManyField(to='userapp.PhotoUser'),
        ),
        migrations.RemoveField(
            model_name='photo',
            name='upload_list',
        ),
        migrations.AddField(
            model_name='photo',
            name='upload_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='photoapp.UploadList'),
        ),
    ]
