# Generated by Django 2.0.5 on 2020-06-24 02:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_photouser_upload_lists'),
        ('photoapp', '0009_auto_20200623_1628'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadlist',
            name='date_upload',
        ),
        migrations.RemoveField(
            model_name='uploadlist',
            name='photos',
        ),
        migrations.AddField(
            model_name='uploadlist',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.RemoveField(
            model_name='uploadlist',
            name='user',
        ),
        migrations.AddField(
            model_name='uploadlist',
            name='user',
            field=models.ForeignKey(default='some_user', on_delete=django.db.models.deletion.CASCADE, to='userapp.PhotoUser'),
            preserve_default=False,
        ),
    ]
