# Generated by Django 2.0.5 on 2020-06-24 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0010_auto_20200624_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadlist',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.PhotoUser'),
        ),
    ]
