# Generated by Django 2.0.5 on 2020-06-24 03:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0011_auto_20200624_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadlist',
            name='photos',
            field=models.ManyToManyField(to='photoapp.Photo'),
        ),
        migrations.AlterField(
            model_name='uploadlist',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 24, 3, 36, 55, 353186, tzinfo=utc)),
        ),
    ]
