# Generated by Django 2.0.5 on 2020-06-24 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_photouser_upload_lists'),
        ('photoapp', '0013_auto_20200624_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadlist',
            name='photos',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='upload_list',
        ),
        migrations.AddField(
            model_name='photo',
            name='upload_list',
            field=models.ManyToManyField(to='photoapp.UploadList'),
        ),
        migrations.RemoveField(
            model_name='uploadlist',
            name='user',
        ),
        migrations.AddField(
            model_name='uploadlist',
            name='user',
            field=models.ManyToManyField(to='userapp.PhotoUser'),
        ),
    ]
