# Generated by Django 2.0.5 on 2020-06-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0014_auto_20200624_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadlist',
            name='image',
            field=models.ManyToManyField(to='photoapp.Photo'),
        ),
    ]
