# Generated by Django 2.0.5 on 2020-06-26 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0015_uploadlist_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadlist',
            old_name='image',
            new_name='images',
        ),
    ]
