# Generated by Django 2.0.5 on 2020-06-23 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0008_auto_20200623_1249'),
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photouser',
            name='upload_lists',
            field=models.ManyToManyField(to='photoapp.UploadList'),
        ),
    ]
