# Generated by Django 2.2.10 on 2020-05-29 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photouser',
            name='time_for_clear_messages',
            field=models.IntegerField(default=60),
        ),
    ]
