# Generated by Django 2.2.10 on 2020-04-13 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20200413_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photouser',
            name='date',
        ),
        migrations.AddField(
            model_name='photouser',
            name='date',
            field=models.ManyToManyField(blank=True, null=True, to='userapp.Photo'),
        ),
    ]
