# Generated by Django 2.2.10 on 2020-04-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20200413_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photouser',
            name='date',
            field=models.ManyToManyField(to='userapp.Photo'),
        ),
    ]
