# Generated by Django 2.2.10 on 2020-04-13 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoapp', '0001_initial'),
        ('userapp', '0004_auto_20200413_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photouser',
            name='date',
        ),
        migrations.AddField(
            model_name='photouser',
            name='image',
            field=models.ManyToManyField(to='photoapp.Photo'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
